name: deeix-chat

services:
    app:
        image: ghcr.io/deeix-ai/deeix-chat:latest
        network_mode: host
        environment:
            - JWT_SECRET
            - DATA_ENCRYPTION_KEY
            - CORS_ALLOW_ORIGIN
            - PUBLIC_API_BASE_URL
            - PUBLIC_WEB_BASE_URL
        container_name: deeix-chat-app
        volumes:
            - app_storage:/app/storage
            - app_data:/app/data
            - ./config.yaml:/app/config.yaml:ro

volumes:
    app_storage:
        name: deeix-chat-app-storage
    app_data:
        name: deeix-chat-app-data
